### PR TITLE
Fix ``JSONBodyMatcher`` to work with requests 2.11+

### LINKED ISSUE #1: Issues with json matcher
I'm trying to use the awesome MultipartFormDataBodyMatcher you recently wrote and am running into some issues.

On the line `request.body.encode('utf-8')`, I receive a `AttributeError: 'bytes' object has no attribute 'encode'` in python3.4 when attempting to match the existing cassette. In python 2.7 the matching exception is `UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 615: ordinal not in range(128)`. On py 2.7 the following deprecation warning is emitted (I'm not sure of its source):

```
/Users/bboe/.venv/p27/lib/python2.7/site-packages/requests-2.7.0-py2.7.egg/requests/packages/urllib3/contrib/pyopenssl.py:198: DeprecationWarning: unicode for buf is no longer accepted, use bytes
```

Below is the request that is saved in the cassette:

``` json
{
            "recorded_at": "2015-06-25T06:38:06",
            "request": {
                "body": {
                    "encoding": "utf-8",
                    "string": "--e3f99acd801b4505a9e9badc8ca979a9\r\nContent-Disposition: form-data; name=\"img_type\"\r\n\r\njpg\r\n--e3f99acd801b4505a9e9badc8ca979a9\r\nContent-Disposition: form-data; name=\"header\"\r\n\r\n1\r\n--e3f99acd801b4505a9e9badc8ca979a9\r\nContent-Disposition: form-data; name=\"r\"\r\n\r\nreddit_api_test\r\n--e3f99acd801b4505a9e9badc8ca979a9\r\nContent-Disposition: form-data; name=\"uh\"\r\n\r\nr7blffd0gne125077e056d9ac6f04a24a9ce130f8da0657878\r\n--e3f99acd801b4505a9e9badc8ca979a9\r\nContent-Disposition: form-data; name=\"api_type\"\r\n\r\njson\r\n--e3f99acd801b4505a9e9badc8ca979a9\r\nContent-Disposition: form-data; name=\"file\"; filename=\"white-square.jpg\"\r\n\r\n\ufffd\ufffd\ufffd\ufffd\u0000\u0010JFIF\u0000\u0001\u0001\u0001\u0000H\u0000H\u0000\u0000\ufffd\ufffd\u0000C\u0000\u0006\u0004\u0005\u0006\u0005\u0004\u0006\u0006\u0005\u0006\u0007\u0007\u0006\b\n\u0010\n\n\t\t\n\u0014\u000e\u000f\f\u0010\u0017\u0014\u0018\u0018\u0017\u0014\u0016\u0016\u001a\u001d%\u001f\u001a\u001b#\u001c\u0016\u0016 , #&')*)\u0019\u001f-0-(0%()(\ufffd\ufffd\u0000\u000b\b\u0001,\u0001,\u0001\u0001\u0011\u0000\ufffd\ufffd\u0000\u0015\u0000\u0001\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\b\ufffd\ufffd\u0000\u0014\u0010\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\ufffd\ufffd\u0000\b\u0001\u0001\u0000\u0000?\u0000\ufffd@\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u007f\ufffd\ufffd\r\n--e3f99acd801b4505a9e9badc8ca979a9--\r\n"
                },
                "headers": {
                    "Accept": [
                        "*/*"
                    ],
                    "Accept-Encoding": [
                        "gzip, deflate"
                    ],
                    "Connection": [
                        "keep-alive"
                    ],
                    "Content-Length": [
                        "1177"
                    ],
                    "Content-Type": [
                        "multipart/form-data; boundary=e3f99acd801b4505a9e9badc8ca979a9"
                    ],
                    "Cookie": [
                        "reddit_session=OMITTED"
                    ],
                    "User-Agent": [
                        "PRAW_test_suite PRAW/3.0.0 Python/2.7.9 Darwin-14.3.0-x86_64-i386-64bit"
                    ]
                },
                "method": "POST",
                "uri": "https://api.reddit.com/api/upload_sr_img"
            },
            "response": {
                "body": {
                    "base64_string": "H4sIAAAAAAAAA6pWSi0qyi8qVrJSiI7VUVDKzE2PLy5KVrJSUMooKSmw0tdP0ivJKM1NKtYrSk1JySzJTU3JTNRLzs/VN3Q38TVKD4jPDNANMiuK8vNNKfePzywu9fP0TIwv9a8ydPY0dIzKNogvSNbLKkhXqgUAAAD//wMAMIJgGWwAAAA=",
                    "encoding": "UTF-8"
                },
                "headers": {
                    "cache-control": [
                        "private, no-cache",
                        "no-cache"
                    ],
                    "cf-ray": [
                        "1fbeaae279190d97-SJC"
                    ],
                    "connection": [
                        "keep-alive"
                    ],
                    "content-encoding": [
                        "gzip"
                    ],
                    "content-type": [
                        "application/json; charset=UTF-8"
                    ],
                    "date": [
                        "Thu, 25 Jun 2015 06:38:05 GMT"
                    ],
                    "pragma": [
                        "no-cache"
                    ],
                    "server": [
                        "cloudflare-nginx"
                    ],
                    "transfer-encoding": [
                        "chunked"
                    ],
                    "x-content-type-options": [
                        "nosniff"
                    ],
                    "x-frame-options": [
                        "SAMEORIGIN"
                    ],
                    "x-moose": [
                        "majestic"
                    ],
                    "x-ratelimit-remaining": [
                        "292"
                    ],
                    "x-ratelimit-reset": [
                        "115"
                    ],
                    "x-ratelimit-used": [
                        "8"
                    ],
                    "x-ua-compatible": [
                        "IE=edge"
                    ],
                    "x-xss-protection": [
                        "1; mode=block"
                    ]
                },
                "status": {
                    "code": 200,
                    "message": "OK"
                },
                "url": "https://api.reddit.com/api/upload_sr_img"
            }
```

### PR DESCRIPTION
**Pull request by bboe**
Resolve #1

### CODE REVIEW

**Comment by sigmavirus24** [comment]
✨ 🍰 ✨ You're awesome!
